# Analisando dados de Futebol

In [1]:
# Importando bibliotecas necessarias 

import basedosdados as bd
import pandas as pd

In [2]:
# CAROL: silken-math-296613 | CAIO: futebol-394512
# Para carregar o dado direto no pandas

df = bd.read_table(dataset_id='mundo_transfermarkt_competicoes',
                    table_id='brasileirao_serie_a',
                    billing_project_id="futebol-394512")
df.head()

Downloading: 100%|██████████████████████| 7890/7890 [00:03<00:00, 2597.32rows/s]

,ano_campeonato,data,rodada,estadio,arbitro,publico,publico_max,time_man,time_vis,tecnico_man,...,chutes_bola_parada_man,chutes_bola_parada_vis,defesas_man,defesas_vis,impedimentos_man,impedimentos_vis,chutes_man,chutes_vis,chutes_fora_man,chutes_fora_vis
0,2009,2009-06-21,7,Estádio Municipal Paulo Machado de Carvalho,Marcelo de Lima Henrique,15371,<NA>,Corinthians,São Paulo,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2009,2009-06-27,8,Estádio Cícero Pompeu de Toledo,André Luiz de Freitas Castro,7977,<NA>,São Paulo,Náutico,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2009,2009-06-28,8,Allianz Parque,Leonardo Gaciba da Silva,8277,<NA>,Palmeiras,Santos FC,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2009,2009-07-05,9,Estádio Major Antônio Couto Pereira,Leandro Pedro Vuaden,21704,<NA>,Coritiba FC,São Paulo,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2009,2009-07-11,10,Allianz Parque,Wagner Tardelli Azevedo,7800,<NA>,Palmeiras,Náutico,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [3]:
df.columns

Index(['ano_campeonato', 'data', 'rodada', 'estadio', 'arbitro', 'publico',
       'publico_max', 'time_man', 'time_vis', 'tecnico_man', 'tecnico_vis',
       'colocacao_man', 'colocacao_vis', 'valor_equipe_titular_man',
       'valor_equipe_titular_vis', 'idade_media_titular_man',
       'idade_media_titular_vis', 'gols_man', 'gols_vis', 'gols_1_tempo_man',
       'gols_1_tempo_vis', 'escanteios_man', 'escanteios_vis', 'faltas_man',
       'faltas_vis', 'chutes_bola_parada_man', 'chutes_bola_parada_vis',
       'defesas_man', 'defesas_vis', 'impedimentos_man', 'impedimentos_vis',
       'chutes_man', 'chutes_vis', 'chutes_fora_man', 'chutes_fora_vis'],
      dtype='object')

In [4]:
# Analisando a tabela extraida do site basedosdados.org

df.describe()

,ano_campeonato,rodada,publico,publico_max,colocacao_man,colocacao_vis,valor_equipe_titular_man,valor_equipe_titular_vis,idade_media_titular_man,idade_media_titular_vis,...,chutes_bola_parada_man,chutes_bola_parada_vis,defesas_man,defesas_vis,impedimentos_man,impedimentos_vis,chutes_man,chutes_vis,chutes_fora_man,chutes_fora_vis
count,7890.0,7890.0,6179.0,3637.0,6180.0,6180.0,5792.0,5792.0,5790.000000,5790.000000,...,1601.0,1601.0,1601.0,1601.0,1601.0,1601.0,1601.0,1601.0,1601.0,1601.0
mean,2012.423574,19.32256,15200.864379,43695.291174,10.643042,10.356958,18291679.903315,17831222.375691,27.212729,27.108791,...,14.034354,14.341037,2.806996,3.518426,1.473454,1.394129,12.564647,9.860712,5.951905,4.667708
std,5.938016,11.013561,13464.552666,19822.444624,5.759806,5.770136,14700869.339698,14027418.35279,1.580528,1.618188,...,4.46158,4.448019,1.86,2.193414,1.375936,1.290907,6.246777,5.319536,2.827907,2.558713
min,2003.0,1.0,0.0,5000.0,1.0,1.0,50000.0,50000.0,20.400000,20.500000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,2007.0,10.0,5524.5,24584.0,6.0,5.0,7550000.0,7480000.0,26.200000,26.000000,...,11.0,11.0,1.0,2.0,0.0,0.0,8.0,6.0,4.0,3.0
50%,2012.0,19.0,12064.0,43600.0,11.0,10.0,14000000.0,13550000.0,27.200000,27.100000,...,14.0,14.0,3.0,3.0,1.0,1.0,12.0,10.0,6.0,4.0
75%,2018.0,29.0,21204.0,57483.0,16.0,15.0,25550000.0,24850000.0,28.300000,28.200000,...,17.0,17.0,4.0,5.0,2.0,2.0,17.0,13.0,8.0,6.0
max,2023.0,38.0,82044.0,87101.0,20.0,20.0,100500000.0,96000000.0,32.900000,32.300000,...,30.0,30.0,12.0,13.0,8.0,8.0,37.0,31.0,21.0,14.0

In [5]:
# Limpando a base para analisar somente o ano corrente 

df_2023 = df[df['ano_campeonato'] == 2023]
df_2023.head()

,ano_campeonato,data,rodada,estadio,arbitro,publico,publico_max,time_man,time_vis,tecnico_man,...,chutes_bola_parada_man,chutes_bola_parada_vis,defesas_man,defesas_vis,impedimentos_man,impedimentos_vis,chutes_man,chutes_vis,chutes_fora_man,chutes_fora_vis
5852,2023,2023-04-24,2,Estádio Serra Dourada,Bruno Arleu de Araújo,10162,14525,Goiás,Corinthians,Émerson Ávila,...,21,20,1,4,4,1,18,10,6,4
5853,2023,2023-05-07,4,Estádio Serra Dourada,Wagner do Nascimento Magalhães,13789,14525,Goiás,Palmeiras,Émerson Ávila,...,29,13,3,4,1,1,15,16,7,5
5854,2023,2023-05-14,6,Estádio Serra Dourada,Rafael Rodrigo Klein,9092,14525,Goiás,Botafogo,Émerson Ávila,...,18,20,1,2,2,2,7,17,2,10
5855,2023,2023-06-04,9,Estádio Serra Dourada,Marcelo de Lima Henrique,6987,14525,Goiás,Cuiabá-MT,Émerson Ávila,...,14,18,7,3,2,1,11,15,7,2
5856,2023,2023-06-11,10,Estádio Serra Dourada,Leandro Pedro Vuaden,10260,14525,Goiás,Fluminense,Émerson Ávila,...,23,15,2,7,5,1,22,14,9,5

### Quais times possues as maiores médias de público?

In [6]:
# Pegando a media de publico presente dos times mandantes 

media_publico = df_2023.groupby('time_man')['publico'].mean().round(1).sort_values(ascending=False)
print(media_publico)

time_man
Flamengo         55673.7
São Paulo        49359.6
Corinthians      38877.2
Palmeiras        37576.4
Fortaleza        36774.4
Fluminense       36179.0
EC Bahia         36080.6
Atlético-MG      33623.8
Cruzeiro         28941.6
Grêmio           27800.0
Internacional    25112.4
Athletico-PR     24836.0
Vasco da Gama    24549.5
Coritiba FC      23214.4
Botafogo         20007.5
Cuiabá-MT        12835.2
Santos           10516.0
Goiás            10058.0
América-MG        5211.2
RB Bragantino     4172.6
Name: publico, dtype: Float64

### Quais times fizeram mais gols dentro de casa? (Melhores ataques mandantes)

In [7]:
# Somando a quantidade de gols dos times mandantes

gols = df_2023.groupby('time_man')['gols_man'].sum()
gols = gols.sort_values(ascending=False)
print(gols)

time_man
Botafogo         12
Palmeiras        12
Flamengo         12
São Paulo        11
EC Bahia          9
Athletico-PR      9
Grêmio            9
RB Bragantino     8
América-MG        7
Goiás             7
Santos            7
Internacional     7
Fluminense        7
Fortaleza         7
Corinthians       7
Atlético-MG       7
Cuiabá-MT         3
Cruzeiro          3
Coritiba FC       3
Vasco da Gama     3
Name: gols_man, dtype: Int64

### Quais times tiveram que defender mais fora de casa?

In [8]:
defesas = df_2023.groupby('time_vis')['defesas_vis'].sum()
defesas = defesas.sort_values(ascending=False)
print(defesas)

time_vis
Fluminense       35
Vasco da Gama    30
Fortaleza        29
Santos           29
Cuiabá-MT        23
Botafogo         23
Athletico-PR     21
Coritiba FC      19
EC Bahia         19
Goiás            18
Palmeiras        18
Grêmio           18
Atlético-MG      17
Cruzeiro         17
Corinthians      17
América-MG       17
São Paulo        16
Internacional    15
RB Bragantino    14
Flamengo         12
Name: defesas_vis, dtype: Int64

### Quais são os times mais violentos? (com mais faltas)

In [9]:
# Separando as faltas por time enquanto mandante e visitando para calcular o total de faltas de cada um 
df_mandantes = df_2023.groupby('time_man')['faltas_man'].sum()
df_visitantes = df_2023.groupby('time_vis')['faltas_vis'].sum()

df_mandantes = pd.DataFrame(df_mandantes)
df_mandantes.reset_index(level=0, inplace=True)
df_visitantes = pd.DataFrame(df_visitantes)
df_visitantes.reset_index(level=0, inplace=True)

df_final = pd.merge(df_mandantes, df_visitantes, left_on='time_man', right_on='time_vis', how='left')
df_final['faltas_total'] = df_final['faltas_man'] + df_final['faltas_vis']
df_final = df_final[['time_man','faltas_total']].rename(columns={'time_man': 'time'})
print(df_final)

             time  faltas_total
0      América-MG           159
1    Athletico-PR           135
2     Atlético-MG           166
3        Botafogo           146
4     Corinthians           134
5     Coritiba FC           159
6        Cruzeiro           151
7       Cuiabá-MT           128
8        EC Bahia           163
9        Flamengo           151
10     Fluminense           126
11      Fortaleza           124
12          Goiás           157
13         Grêmio           130
14  Internacional           121
15      Palmeiras           167
16  RB Bragantino           173
17         Santos           153
18      São Paulo           143
19  Vasco da Gama           161

### Analisando o Fluminense em casa

In [10]:
fluminense = df_2023[(df_2023['time_man'] == 'Fluminense')]
fluminense = fluminense.filter(like='_man')
fluminense.describe()

# vai mal

,colocacao_man,valor_equipe_titular_man,idade_media_titular_man,gols_man,gols_1_tempo_man,escanteios_man,faltas_man,chutes_bola_parada_man,defesas_man,impedimentos_man,chutes_man,chutes_fora_man
count,4.0,4.0,4.000000,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
mean,4.25,36900000.0,30.775000,1.75,1.0,8.0,12.25,14.75,1.5,1.5,14.0,6.5
std,2.986079,5444569.159569,0.457347,0.5,0.816497,1.825742,1.707825,5.123475,1.290994,1.290994,6.683313,2.516611
min,1.0,29950000.0,30.200000,1.0,0.0,6.0,10.0,9.0,0.0,0.0,7.0,4.0
25%,2.5,35200000.0,30.575000,1.75,0.75,6.75,11.5,11.25,0.75,0.75,10.75,5.5
50%,4.0,37200000.0,30.800000,2.0,1.0,8.0,12.5,15.0,1.5,1.5,13.0,6.0
75%,5.75,38900000.0,31.000000,2.0,1.25,9.25,13.25,18.5,2.25,2.25,16.25,7.0
max,8.0,43250000.0,31.300000,2.0,2.0,10.0,14.0,20.0,3.0,3.0,23.0,10.0

### Quais times tem mais impedimentos fora de casa?

Vasco é mt azarado kkkkk

In [11]:
impedimentos = df_2023.groupby('time_vis')['impedimentos_vis'].sum()
impedimentos = impedimentos.sort_values(ascending=False)
print(impedimentos)

time_vis
Cruzeiro         18
Santos           16
Vasco da Gama    14
Goiás            13
Cuiabá-MT        12
Fluminense       12
Atlético-MG      12
Athletico-PR     10
Fortaleza        10
Palmeiras         9
São Paulo         9
América-MG        9
Coritiba FC       8
Flamengo          8
Botafogo          8
Grêmio            8
Internacional     8
RB Bragantino     8
EC Bahia          7
Corinthians       4
Name: impedimentos_vis, dtype: Int64

### Quais os times com titulares mais velhos?

In [12]:
df_2023.groupby('time_man').agg({'idade_media_titular_man':'mean'}).sort_values(by='idade_media_titular_man', ascending=False)

               idade_media_titular_man
time_man
Fluminense                   30.775000
América-MG                   30.716667
Fortaleza                    29.800000
Botafogo                     29.033333
Atlético-MG                  28.940000
Cruzeiro                     28.780000
Cuiabá-MT                    28.775000
Grêmio                       28.720000
Internacional                28.580000
Goiás                        28.520000
Palmeiras                    27.820000
Coritiba FC                  27.220000
São Paulo                    27.220000
Corinthians                  26.820000
EC Bahia                     26.760000
Flamengo                     26.650000
Athletico-PR                 26.200000
Santos                       26.160000
Vasco da Gama                25.375000
RB Bragantino                24.660000

### Quais são os times mais ricos?

A SAF do Vasco é rica mesmo quem diria (caloteiros)

In [13]:
df_2023.groupby('time_man').agg({'valor_equipe_titular_man':'mean'}).round(1).sort_values(by='valor_equipe_titular_man', ascending=False)

               valor_equipe_titular_man
time_man
Flamengo                     83608333.3
Palmeiras                    80840000.0
Athletico-PR                 47230000.0
Corinthians                  45640000.0
Atlético-MG                  44500000.0
Vasco da Gama                43100000.0
Fluminense                   36900000.0
Santos                       33820000.0
Internacional                31860000.0
São Paulo                    30260000.0
RB Bragantino                28360000.0
Grêmio                       26040000.0
Botafogo                     24483333.3
EC Bahia                     21240000.0
Cruzeiro                     17410000.0
Coritiba FC                  17270000.0
Fortaleza                    13730000.0
Goiás                        10180000.0
América-MG                    8175000.0
Cuiabá-MT                     7082500.0

### Qual árbitro apitou mais?

In [14]:
df_2023['arbitro'].value_counts()

Rafael Rodrigo Klein                   8
Braulio da Silva Machado               8
Raphael Claus                          8
Wilton Sampaio                         8
Flavio Rodrigues de Souza              6
Rodrigo Jose Pereira de Lima           6
Savio Pereira Sampaio                  6
Paulo Cesar Zanovelli                  6
Bruno Arleu de Araújo                  5
Edina Alves Batista                    5
Ramon Abatti                           5
Anderson Daronco                       5
Wagner do Nascimento Magalhães         4
Bruno Mota Correia                     3
Denis Ribeiro Serafim                  3
Leandro Pedro Vuaden                   3
Luiz Flávio de Oliveira                2
João Vitor Gobi                        2
Felipe Fernandes                       2
Marcelo de Lima Henrique               1
Caio Max Augusto Vieira                1
André Luiz Skettino Policarpo Bento    1
Vinicius Gonçalves Dias Araujo         1
Maguielson Lima Barbosa                1
Name: arbitro, dtype: int64

In [20]:
df_2023[['time_man', 'arbitro']].value_counts().head(40)

time_man       arbitro
Flamengo       Savio Pereira Sampaio             2
Fortaleza      Edina Alves Batista               2
Grêmio         Wilton Sampaio                    2
Cruzeiro       Flavio Rodrigues de Souza         2
               Savio Pereira Sampaio             2
Atlético-MG    Raphael Claus                     2
Grêmio         Flavio Rodrigues de Souza         1
Internacional  Rodrigo Jose Pereira de Lima      1
               Ramon Abatti                      1
               Edina Alves Batista               1
               Bruno Arleu de Araújo             1
Grêmio         Paulo Cesar Zanovelli             1
               Bruno Mota Correia                1
Palmeiras      Braulio da Silva Machado          1
Goiás          Wagner do Nascimento Magalhães    1
               Rafael Rodrigo Klein              1
               Marcelo de Lima Henrique          1
               Leandro Pedro Vuaden              1
               Bruno Arleu de Araújo             1
Fortaleza      Raphael Claus                     1
               Paulo Cesar Zanovelli             1
               João Vitor Gobi                   1
Fluminense     Wilton Sampaio                    1
Internacional  Wagner do Nascimento Magalhães    1
Palmeiras      Felipe Fernandes                  1
Fluminense     Paulo Cesar Zanovelli             1
Santos         Raphael Claus                     1
Vasco da Gama  Rafael Rodrigo Klein              1
               Flavio Rodrigues de Souza         1
               Braulio da Silva Machado          1
São Paulo      Wagner do Nascimento Magalhães    1
               Raphael Claus                     1
               Rafael Rodrigo Klein              1
               Leandro Pedro Vuaden              1
               Braulio da Silva Machado          1
Santos         Wagner do Nascimento Magalhães    1
               Paulo Cesar Zanovelli             1
Palmeiras      Paulo Cesar Zanovelli             1
Santos         Braulio da Silva Machado          1
               Anderson Daronco                  1
dtype: int64

In [19]:
df_2023[(df['time_man']=='Flamengo') | (df['time_vis']=='Flamengo')]['arbitro'].value_counts()

Savio Pereira Sampaio           2
Paulo Cesar Zanovelli           1
Rodrigo Jose Pereira de Lima    1
Edina Alves Batista             1
Rafael Rodrigo Klein            1
Luiz Flávio de Oliveira         1
Raphael Claus                   1
Ramon Abatti                    1
Braulio da Silva Machado        1
Name: arbitro, dtype: int64

### Quais times têm mais gols?

- Gols totais como time visitante + mandante
- Gols no primeiro tempo
- Gols no segundo tempo

In [35]:
mandante = df_2023.groupby('time_man').agg({'gols_1_tempo_man':'sum', 'gols_man':'sum'}).reset_index()
visitante = df_2023.groupby('time_vis').agg({'gols_1_tempo_vis':'sum', 'gols_vis':'sum'}).reset_index()

gols1 = mandante.merge(visitante, how='left', left_on='time_man', right_on='time_vis')
gols1['total_gols'] = gols1['gols_man'] + gols1['gols_vis']
gols1['gols_1_tempo'] = gols1['gols_1_tempo_man'] + gols1['gols_1_tempo_vis']
gols1['gols_2_tempo'] = gols1['total_gols'] - gols1['gols_1_tempo']

gols1 = gols1.iloc[:,[0,2,5,6,7,8]]
gols1.sort_values(by='total_gols', ascending=False)

         time_man  gols_man  gols_vis  total_gols  gols_1_tempo  gols_2_tempo
15      Palmeiras        12        10          22             9            13
9        Flamengo        12         9          21            12             9
3        Botafogo        12         6          18             9             9
10     Fluminense         7         9          16             7             9
18      São Paulo        11         4          15             7             8
16  RB Bragantino         8         7          15             6             9
2     Atlético-MG         7         7          14             8             6
6        Cruzeiro         3        11          14             6             8
13         Grêmio         9         5          14             9             5
1    Athletico-PR         9         5          14             5             9
11      Fortaleza         7         5          12             3             9
0      América-MG         7         4          11             5             6
8        EC Bahia         9         2          11             7             4
14  Internacional         7         3          10             3             7
19  Vasco da Gama         3         7          10             7             3
12          Goiás         7         2           9             5             4
7       Cuiabá-MT         3         6           9             4             5
17         Santos         7         2           9             6             3
4     Corinthians         7         2           9             2             7
5     Coritiba FC         3         5           8             4             4